name: ECPL FrontEnd Website Deploy


trigger: none

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-calm-wave-04545e203-variable-group
  steps:
  - checkout: self
    submodules: true
  - task: NodeTool@0
    displayName: 'Use Node.js'
    inputs:
      versionSpec: '18.x'      # or 20.x depending on your app

  # Install dependencies
  - script: |
      npm install --legacy-peer-deps 
    displayName: 'Install dependencies'

  # Build SPA
  - script: |
      npm run build
    displayName: 'Build app'


  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/out'
      output_location: '/out'
      skip_app_build: true
      skip_api_build: true
      verbose: true
      is_static_export: true
      azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_WAVE_04545E203)'

